import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import ReactFlow, { Background, Controls, MarkerType } from 'reactflow';
import 'reactflow/dist/style.css';
import { Activity, ArrowUpRight, CheckCircle2, ChevronRight, CircleAlert, Network, Radar, ShieldCheck, Sparkles } from 'lucide-react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from 'recharts';
import { api } from './services/api';
import type { AttackPath, Environment } from './types';
import './styles.css';

const colors: Record<string, string> = { Critical: '#d03238', High: '#e97827', Medium: '#ffd11a', Low: '#054d28', Informational: '#868685' };
type Analysis = { paths: AttackPath[]; summary: { attack_paths: number; critical_paths: number; highest_risk: number; risk_distribution: Record<string, number> }; recommendations: { priority: string; type: string; text: string }[] };

function App() {
  const [environment, setEnvironment] = useState<Environment>(); const [analysis, setAnalysis] = useState<Analysis>(); const [selected, setSelected] = useState<AttackPath>(); const [entry, setEntry] = useState('internet'); const [target, setTarget] = useState('db01'); const [whatIf, setWhatIf] = useState<{ paths_eliminated: number; risk_reduction: number }>();
  const runAnalysis = () => api.analyze(entry, target).then(result => { setAnalysis(result); setSelected(result.paths[0]); setWhatIf(undefined); });
  useEffect(() => { api.environment().then(setEnvironment); }, []); useEffect(() => { if (environment) runAnalysis(); }, [environment]);
  const flowNodes = useMemo(() => environment?.nodes.map((node, index) => ({ id: node.id, position: { x: (index % 4) * 208, y: Math.floor(index / 4) * 122 }, data: { label: <div className="flow-label"><b>{node.name}</b><small>{node.type} · C{node.criticality}</small></div> }, style: { background: node.kind === 'identity' ? '#e2f6d5' : node.type === 'Internet' ? '#ffd11a' : '#ffffff', color: '#0e0f0c', border: `1px solid ${selected?.node_ids.includes(node.id) ? '#163300' : '#d4d8d0'}`, boxShadow: selected?.node_ids.includes(node.id) ? '0 6px 0 #9fe870' : 'none', borderRadius: 12, padding: 11, width: 172 } })) ?? [], [environment, selected]);
  const flowEdges = useMemo(() => environment?.relationships.map(edge => ({ id: edge.id, source: edge.source, target: edge.target, label: edge.type.replaceAll('_', ' '), animated: selected?.relationship_ids.includes(edge.id), style: { stroke: selected?.relationship_ids.includes(edge.id) ? '#163300' : '#a4aaa2', strokeWidth: selected?.relationship_ids.includes(edge.id) ? 2.6 : 1.2 }, markerEnd: { type: MarkerType.ArrowClosed, color: selected?.relationship_ids.includes(edge.id) ? '#163300' : '#a4aaa2' }, labelStyle: { fill: '#454745', fontSize: 9, fontWeight: 700 } })) ?? [], [environment, selected]);
  if (!environment) return <div className="loading"><Radar /> Preparing the security workspace</div>;
  const paths = analysis?.paths ?? []; const summary = analysis?.summary; const chart = Object.entries(summary?.risk_distribution ?? {}).map(([name, value]) => ({ name, value: Number(value) })); const routeName = (id: string) => environment.nodes.find(node => node.id === id)?.name ?? id;
  return <main><header className="topbar"><a className="brand" href="#overview"><span className="brand-mark"><Network size={17} /></span>attackpath<span>x</span></a><div className="top-status"> Simulated environment <span className="top-divider" /> Last analysis: just now</div><button className="run-button" onClick={runAnalysis}><Sparkles size={16} /> Run analysis</button></header>
    <section className="hero" id="overview"><div><p className="kicker">ATTACK PATH INTELLIGENCE</p><h1>See the route.<br /><em>Break the chain.</em></h1><p className="hero-copy">Explore how an attacker could move through your environment, then test the controls that stop them.</p></div><div className="hero-score"><span>Highest active risk</span><strong>{summary?.highest_risk ?? '—'}<small>/100</small></strong><div className="meter"><i style={{ width: `${summary?.highest_risk ?? 0}%` }} /></div><b>{summary?.critical_paths ?? 0} critical paths need attention</b></div></section>
    <section className="control-bar"><div className="select-wrap"><span>Attacker begins at</span><select value={entry} onChange={event => setEntry(event.target.value)}>{environment.nodes.map(node => <option key={node.id} value={node.id}>{node.name}</option>)}</select></div><ChevronRight className="arrow" /><div className="select-wrap"><span>Trying to reach</span><select value={target} onChange={event => setTarget(event.target.value)}>{environment.nodes.filter(node => node.criticality >= 7).map(node => <option key={node.id} value={node.id}>{node.name}</option>)}</select></div><p><ShieldCheck size={17} /> Analysis considers vulnerabilities, permissions and exposure.</p></section>
    <section className="metrics"><Metric icon={<Network />} label="Viable paths" value={summary?.attack_paths ?? '—'} caption="to the selected target" /><Metric icon={<CircleAlert />} label="Critical paths" value={summary?.critical_paths ?? '—'} caption="require a control change" danger /><Metric icon={<Activity />} label="Protected assets" value={environment.nodes.filter(node => node.criticality >= 7).length} caption="high-value systems" /><Metric icon={<ShieldCheck />} label="Recommendations" value={analysis?.recommendations.length ?? '—'} caption="prioritized actions" /></section>
    <section className="workspace"><article className="graph-card card"><div className="section-heading"><div><p className="eyebrow">LIVE MAP</p><h2>Environment graph</h2></div><span className="hint"><i /> selected route</span></div><ReactFlow nodes={flowNodes} edges={flowEdges} fitView minZoom={0.3}><Background color="#e8ebe6" gap={18} /><Controls showInteractive={false} /></ReactFlow></article><article className="distribution-card card"><p className="eyebrow">PATH MIX</p><h2>Risk distribution</h2><div className="donut"><ResponsiveContainer width="100%" height={190}><PieChart><Pie data={chart} dataKey="value" nameKey="name" innerRadius={59} outerRadius={81} paddingAngle={3}>{chart.map(item => <Cell key={item.name} fill={colors[item.name]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><strong>{summary?.attack_paths ?? 0}<small> routes</small></strong></div><div className="legend">{chart.map(item => <span key={item.name}><i style={{ background: colors[item.name] }} />{item.name}<b>{item.value}</b></span>)}</div></article></section>
    <section className="investigation"><article className="paths-card card"><div className="section-heading"><div><p className="eyebrow">PRIORITY QUEUE</p><h2>Routes to investigate</h2></div><span className="path-count">{paths.length} active</span></div><div className="path-list">{paths.map((path, index) => <button key={path.id} className={`path-row ${selected?.id === path.id ? 'is-selected' : ''}`} onClick={() => { setSelected(path); setWhatIf(undefined); }}><span className="path-index">0{index + 1}</span><span className="severity" style={{ color: colors[path.severity] }}>{path.severity}</span><span className="path-route">{path.node_ids.map(routeName).join('  →  ')}</span><span className="risk-number">{path.risk_score}<small>/100</small></span><ArrowUpRight size={17} /></button>)}</div></article><article className="detail-card card"><p className="eyebrow">PATH BRIEF</p>{selected ? <><div className="detail-risk"><span style={{ background: colors[selected.severity] }} /> {selected.severity} risk <strong>{selected.risk_score}<small>/100</small></strong></div><h2>{routeName(selected.entry_point)} <span>to</span> {routeName(selected.target)}</h2><p className="explanation">{selected.explanation}</p><div className="techniques"><b>MITRE ATT&amp;CK</b>{selected.techniques.map(technique => <code key={technique}>{technique}</code>)}</div><button className="what-if" onClick={() => api.whatIf(selected.relationship_ids[0], 'relationship', entry, target).then(setWhatIf)}><Sparkles size={15} /> Test a control change</button>{whatIf && <div className="what-result"><CheckCircle2 size={18} /><span><b>{whatIf.paths_eliminated} paths removed</b><br />Risk reduced by {whatIf.risk_reduction}%</span></div>}</> : <p>Select a route to inspect it.</p>}</article></section>
    <section className="recommendations"><div><p className="eyebrow">NEXT BEST ACTIONS</p><h2>Start with the changes that make a difference.</h2></div><div className="recommendation-list">{(analysis?.recommendations ?? []).slice(0, 3).map((recommendation, index) => <article key={recommendation.text}><span>0{index + 1}</span><p><b>{recommendation.type} <em>{recommendation.priority}</em></b>{recommendation.text}</p></article>)}</div></section>
  </main>;
}
function Metric({ icon, label, value, caption, danger }: { icon: ReactNode; label: string; value: string | number; caption: string; danger?: boolean }) { return <article className={`metric ${danger ? 'metric-danger' : ''}`}><i>{icon}</i><p>{label}</p><strong>{value}</strong><span>{caption}</span></article>; }
createRoot(document.getElementById('root')!).render(<App />);
